In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime
import statsmodels.graphics.tsaplots
from statsmodels.tsa.stattools import adfuller
from sklearn.model_selection import TimeSeriesSplit
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_squared_error
import statistics

In [10]:
data = pd.read_csv('Data/preprocessed/NP15_rt_series.csv')
data['begin_time'] = pd.to_datetime(data['begin_time'])
data

                begin_time  NP-15 LMP  NP-15 LMP 24hrdiffs
0      2021-01-01 00:00:00   30.76070                  NaN
1      2021-01-01 00:05:00   33.28136                  NaN
2      2021-01-01 00:10:00   33.98668                  NaN
3      2021-01-01 00:15:00   31.35044                  NaN
4      2021-01-01 00:20:00   32.65816                  NaN
...                    ...        ...                  ...
420763 2024-12-31 23:35:00   45.51538             10.83216
420764 2024-12-31 23:40:00   45.51538             11.29885
420765 2024-12-31 23:45:00   46.04096             12.77769
420766 2024-12-31 23:50:00   46.04096             14.07880
420767 2024-12-31 23:55:00   44.56806             12.60590

[420768 rows x 3 columns]

In [11]:
data_train=data.iloc[:336614]
data_train

                begin_time  NP-15 LMP  NP-15 LMP 24hrdiffs
0      2021-01-01 00:00:00   30.76070                  NaN
1      2021-01-01 00:05:00   33.28136                  NaN
2      2021-01-01 00:10:00   33.98668                  NaN
3      2021-01-01 00:15:00   31.35044                  NaN
4      2021-01-01 00:20:00   32.65816                  NaN
...                    ...        ...                  ...
336609 2024-03-14 18:45:00   44.28147              5.00726
336610 2024-03-14 18:50:00   46.01345              6.35837
336611 2024-03-14 18:55:00   46.01345              6.58810
336612 2024-03-14 19:00:00   40.90483              7.68399
336613 2024-03-14 19:05:00   40.90483              8.76569

[336614 rows x 3 columns]