In [14]:
import pandas as pd
import linearmodels as lm

data = pd.read_csv('ITSUR_data.csv')
data.describe()

,NP-15 LMP_da,SP-15 LMP_da,NP-15 LMP_rt,SP-15 LMP_rt,Natural_gas_price,flow_klamath,flow_sacramento,load_PGE,load_SCE,Pacific Gas and Electric Forecast Load (MW),Southern California Edison Forecast Load (MW),solar_mw_NP15,wind_mw_NP15,solar_mw_SP15,wind_mw_SP15,NP15 Solar Generation (MW),SP15 Solar Generation (MW),NP15 Wind Generation (MW),SP15 Wind Generation (MW)
count,403975.000000,403975.000000,403975.000000,403954.000000,403975.000000,403975.000000,403975.000000,403975.000000,403975.000000,403876.000000,403876.000000,403939.000000,403975.000000,403072.000000,403975.000000,403911.000000,403911.000000,401287.000000,401383.000000
mean,40.220724,34.856840,37.215025,31.312198,2.365944,12899.309437,19321.029978,11763.260793,12628.961332,11424.562019,11860.281353,677.650687,462.688927,4242.824676,1347.574083,569.064897,3919.948507,475.141383,1359.864552
std,26.649406,30.652503,29.559195,29.315409,0.812416,21537.507035,10285.115316,2175.003045,2924.290483,2410.314274,2968.079627,787.285364,314.562996,4914.841745,958.160988,671.209095,4638.400752,382.599734,1072.511674
min,-31.707580,-50.526010,-73.952840,-157.098370,1.210000,1940.000000,-5360.000000,5804.000000,6898.000000,4988.950000,6303.010000,0.000000,2.280000,0.000000,1.600000,-307.909700,-93.474700,-20.167350,-31.577960
25%,29.656300,23.695455,27.377880,20.762470,1.940000,2820.000000,12800.000000,10226.000000,10463.000000,9753.430000,9761.910000,0.000000,176.575000,0.000000,484.380000,-0.390390,-36.411620,119.952250,327.017390
50%,38.154660,35.813130,36.063180,33.419130,2.200000,4760.000000,18400.000000,11363.000000,11890.000000,11037.690000,11038.590000,64.990000,414.290000,529.090000,1183.880000,105.727070,325.250320,393.159900,1189.302760
75%,48.245760,45.792190,46.468070,43.530940,2.580000,14000.000000,22000.000000,12738.000000,14134.000000,12469.290000,12932.270000,1604.190000,745.640000,9524.650000,2095.820000,1302.462450,8770.770535,815.479190,2304.864410
max,1262.849100,1300.110000,1992.543500,1870.605200,13.200000,189000.000000,87500.000000,22371.000000,25394.000000,22599.960000,25226.770000,2091.380000,1298.770000,12827.360000,3785.210000,1925.043940,12570.905160,2252.736830,3891.374970

In [17]:
data

,begin_time,NP-15 LMP_da,SP-15 LMP_da,NP-15 LMP_rt,SP-15 LMP_rt,Natural_gas_price,flow_klamath,flow_sacramento,load_PGE,load_SCE,Pacific Gas and Electric Forecast Load (MW),Southern California Edison Forecast Load (MW),solar_mw_NP15,wind_mw_NP15,solar_mw_SP15,wind_mw_SP15,NP15 Solar Generation (MW),SP15 Solar Generation (MW),NP15 Wind Generation (MW),SP15 Wind Generation (MW)
0,2021-03-12 00:00:00,42.96548,40.78043,34.56084,33.48478,2.65,11.9,14.80,9914,9763,10102.72,9686.47,0.0,327.97,0.0,1062.94,-2.69832,-26.29464,526.78168,713.36328
1,2021-03-12 01:00:00,39.48897,37.76416,33.10504,32.01413,2.65,11.9,14.40,9827,9536,9868.57,9474.64,0.0,259.94,0.0,1018.10,-2.66009,-26.30124,405.97186,583.05445
2,2021-03-12 02:00:00,39.09879,37.50715,34.53900,33.43611,2.65,11.9,12.50,9849,9416,9712.50,9339.19,0.0,191.44,0.0,974.17,-2.68074,-26.46864,288.43194,730.31104
3,2021-03-12 03:00:00,39.38309,37.79894,33.62841,32.36996,2.65,11.9,8.93,9939,9475,9715.76,9304.25,0.0,148.07,0.0,935.87,-2.68692,-29.03769,205.85381,709.88240
4,2021-03-12 04:00:00,41.92228,40.13255,34.56917,33.48674,2.65,11.8,6.77,10287,9842,9969.51,9545.95,0.0,134.36,0.0,908.84,-2.58009,-29.40176,173.78675,661.02222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403970,2024-12-31 23:00:00,51.03593,49.97010,46.50217,45.46606,3.40,80.2,54.60,9851,9854,10234.59,10068.75,0.0,88.81,0.0,372.25,-6.57764,-37.71737,61.75742,78.96604
403971,2024-12-31 23:00:00,51.03593,49.97010,46.50217,45.46606,3.40,80.2,54.60,9851,9854,10234.59,10068.75,0.0,88.81,0.0,300.71,-6.57764,-37.71737,61.75742,78.96604
403972,2024-12-31 23:00:00,51.03593,49.97010,46.50217,45.46606,3.40,80.2,54.60,9851,9854,10234.59,10068.75,0.0,88.81,0.0,242.24,-6.57764,-37.71737,61.75742,78.96604
403973,2024-12-31 23:00:00,51.03593,49.97010,46.50217,45.46606,3.40,80.2,54.60,9851,9854,10234.59,10068.75,0.0,88.81,0.0,218.36,-6.57764,-37.71737,61.75742,78.96604
403974,2024-12-31 23:00:00,51.03593,49.97010,46.50217,45.46606,3.40,80.2,54.60,9851,9854,10234.59,10068.75,0.0,88.81,0.0,321.91,-6.57764,-37.71737,61.75742,78.96604

In [20]:
X = data[['Natural_gas_price', 'flow_klamath', 'flow_sacramento',
       'load_PGE', 'load_SCE', 'Pacific Gas and Electric Forecast Load (MW)',
       'Southern California Edison Forecast Load (MW)', 'solar_mw_NP15',
       'wind_mw_NP15', 'solar_mw_SP15', 'wind_mw_SP15']]
#X = data[['Natural_gas_price', 'flow_klamath', 'flow_sacramento',
#       'load_PGE', 'load_SCE', 'Pacific Gas and Electric Forecast Load (MW)',
#       'Southern California Edison Forecast Load (MW)', 'solar_mw_NP15',
#       'wind_mw_NP15', 'solar_mw_SP15', 'wind_mw_SP15',
#       'NP15 Solar Generation (MW)', 'SP15 Solar Generation (MW)',
#       'NP15 Wind Generation (MW)', 'SP15 Wind Generation (MW)']]
Y = data[['NP-15 LMP_da', 'SP-15 LMP_da']]
#Y = data[['NP-15 LMP_da', 'SP-15 LMP_da', 'NP-15 LMP_rt', 'SP-15 LMP_rt']]

SUR_obj = lm.system.model.SUR.multivariate_ls(Y, X)
results = SUR_obj.fit(method='gls', iterate=True)

/opt/anaconda3/envs/erdos_spring_2025/lib/python3.12/site-packages/linearmodels/system/model.py:404: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  self._validate_data()

In [21]:
results

                           System GLS Estimation Summary
===================================================================================
Estimator:                        GLS   Overall R-squared:                   0.8245
No. Equations.:                     2   McElroy's R-squared:                 0.4524
No. Observations:              402977   Judge's (OLS) R-squared:             0.5237
Date:                Thu, Apr 03 2025   Berndt's R-squared:                  0.6764
Time:                        18:40:21   Dhrymes's R-squared:                 0.8218
                                        Cov. Estimator:                      robust
                                        Num. Constraints:                      None
                             Equation: NP-15 LMP_da, Dependent Variable: NP-15 LMP_da
=================================================================================================================
                                               Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------
Natural_gas_price                                 5.3784     0.1000     53.768     0.0000      5.1824      5.5745
flow_klamath                                      0.0317     0.0018     18.036     0.0000      0.0283      0.0352
flow_sacramento                                  -0.2535     0.0060    -42.009     0.0000     -0.2654     -0.2417
load_PGE                                         -0.0026     0.0001    -21.095     0.0000     -0.0029     -0.0024
load_SCE                                          0.0020  5.063e-05     38.895     0.0000      0.0019      0.0021
Pacific Gas and Electric Forecast Load (MW)       0.0060     0.0001     54.457     0.0000      0.0058      0.0062
Southern California Edison Forecast Load (MW)    -0.0005  3.925e-05    -12.726     0.0000     -0.0006     -0.0004
solar_mw_NP15                                     0.0074     0.0003     27.630     0.0000      0.0069      0.0080
wind_mw_NP15                                     -0.0187     0.0001    -142.48     0.0000     -0.0190     -0.0185
solar_mw_SP15                                    -0.0037  4.512e-05    -81.836     0.0000     -0.0038     -0.0036
wind_mw_SP15                                     -0.0038  3.511e-05    -107.38     0.0000     -0.0038     -0.0037
                             Equation: SP-15 LMP_da, Dependent Variable: SP-15 LMP_da
=================================================================================================================
                                               Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------------------------------------
Natural_gas_price                                 5.2263     0.1003     52.090     0.0000      5.0297      5.4230
flow_klamath                                     -0.0183     0.0017    -10.819     0.0000     -0.0216     -0.0149
flow_sacramento                                  -0.0977     0.0059    -16.595     0.0000     -0.1092     -0.0862
load_PGE                                         -0.0036     0.0002    -23.094     0.0000     -0.0039     -0.0033
load_SCE                                          0.0013  6.142e-05     21.263     0.0000      0.0012      0.0014
Pacific Gas and Electric Forecast Load (MW)       0.0032     0.0001     22.776     0.0000      0.0029      0.0034
Southern California Edison Forecast Load (MW)     0.0038  4.634e-05     80.987     0.0000      0.0037      0.0038
solar_mw_NP15                                     0.0073     0.0003     27.809     0.0000      0.0068      0.0078
wind_mw_NP15                                     -0.0128     0.0001    -92.433     0.0000     -0.0131     -0.0125
solar_mw_SP15                                    -0.0052  4.621e-05    -111.88     0.0000     -0.0053     -0.0051
wind_mw_SP15                                     -0.0050  3.415e-05    -147.63     0.0000     -0.0051     -0.0050
=================================================================================================================

Covariance Estimator:
Heteroskedastic (Robust) Covariance (Debiased: False, GLS: True)
SystemResults, id: 0x3b7dbd790

In [58]:
import linearmodels as lm
import numpy as np

np.random.seed(215)
n = 500  # sample size
X1 = np.random.normal(0, 1, n)
X2 = np.random.normal(0, 1, n)
X = np.column_stack([X1,X2, np.ones(n)])

epsilon1 = np.random.normal(0, 1, n)
epsilon2 = np.random.normal(0,1,n)

# True model: Y depends on both X1 and X2
Y1 =  1 + 3 * X1 + 1.5 * X2 + epsilon1 + 2*epsilon2
Y2 =  2 + 4*X1 - X2 + epsilon1 - epsilon2


# Fit the full and reduced models

# Note:  I am using statsmodel formulas here, which are similar to R style formulas.
# You could instead build the relevant design matrices (including a column of ones!) and use sm.OLS(Y,X).fit()

# Full model: Y ~ X1 + X2
#data = {'Y': Y, 'X1': X1, 'X2': X2}
#full_model = smf.ols('Y ~ X1 + X2', data=data).fit()

SUR_obj = lm.system.model.SUR({'eq1':{'dependent':Y1, 'exog':X}, 'eq2':{'dependent':Y2, 'exog':X} })
results = SUR_obj.fit(method='gls', iterate=True)
results
#results._sigma

                           System GLS Estimation Summary
===================================================================================
Estimator:                        GLS   Overall R-squared:                   0.7858
No. Equations.:                     2   McElroy's R-squared:                 0.8636
No. Observations:                 500   Judge's (OLS) R-squared:             0.7858
Date:                Mon, Mar 31 2025   Berndt's R-squared:                  0.9528
Time:                        19:20:45   Dhrymes's R-squared:                 0.7858
                                        Cov. Estimator:                      robust
                                        Num. Constraints:                      None
                Equation: eq1, Dependent Variable: dependent_0
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
exog_0.0       2.8351     0.1029     27.540     0.0000      2.6333      3.0368
exog_0.1       1.3798     0.0964     14.316     0.0000      1.1909      1.5687
exog_0.2       1.0814     0.0956     11.318     0.0000      0.8941      1.2687
                Equation: eq2, Dependent Variable: dependent_1
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
exog_1.0       3.9766     0.0697     57.034     0.0000      3.8399      4.1132
exog_1.1      -0.9729     0.0615    -15.807     0.0000     -1.0935     -0.8522
exog_1.2       2.0461     0.0634     32.249     0.0000      1.9217      2.1704
==============================================================================

Covariance Estimator:
Heteroskedastic (Robust) Covariance (Debiased: False, GLS: True)
SystemResults, id: 0x177395f40

In [ ]:
import linearmodels as lm
import numpy as np

np.random.seed(215)
n = 500  # sample size
X1 = np.random.normal(0, 1, n)
X2 = np.random.normal(0, 1, n)
X = np.column_stack([X1,X2, np.ones(n)])

epsilon1 = np.random.normal(0, 1, n)
epsilon2 = np.random.normal(0,1,n)

# True model: Y depends on both X1 and X2
Y1 =  1 + 3 * X1 + 1.5 * X2 + epsilon1 + 2*epsilon2
Y2 =  2 + 4*X1 - X2 + epsilon1 - epsilon2
Y = np.column_stack([Y1, Y2])

SUR_obj = lm.system.model.SUR.multivariate_ls(Y, X)
SUR_obj.fit(method='gls', iterate=True)

             dependent.0  dependent.1
dependent.0     4.586822    -0.984558
dependent.1    -0.984558     2.021708

In [42]:
import pandas as pd
import numpy as np

np.random.seed(215)
n = 70  # sample size
X1 = np.random.normal(0, 1, n)
X2 = np.random.normal(0, 1, n)

epsilon1 = np.random.normal(0, 1, n)
epsilon2 = np.random.normal(0,1,n)

# True model: Y depends on both X1 and X2
Y1 =  1 + 3 * X1 + 1.5 * X2 + epsilon1 + epsilon2
Y2 =  2 + 4*X1 - X2 + epsilon1 - epsilon2

data = pd.DataFrame({"y1":Y1, "y2":Y2, "x1":X1, "x2":X2 })

#data = pd.DataFrame(np.random.randn(500, 4), columns=["y1", "x1_1", "y2", "x2_1"])
from linearmodels.system import SUR
formula = {"eq1": "y1 ~ 1 + x1 + x2", "eq2": "y2 ~ 1 + x1 + x2"}
mod = SUR.from_formula(formula, data)
mod.fit(method='gls', iterate=True)

                           System GLS Estimation Summary
===================================================================================
Estimator:                        GLS   Overall R-squared:                   0.8664
No. Equations.:                     2   McElroy's R-squared:                 0.8566
No. Observations:                  70   Judge's (OLS) R-squared:             0.8664
Date:                Mon, Mar 31 2025   Berndt's R-squared:                  0.9652
Time:                        18:56:32   Dhrymes's R-squared:                 0.8664
                                        Cov. Estimator:                      robust
                                        Num. Constraints:                      None
                    Equation: eq1, Dependent Variable: y1
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      0.7210     0.1772     4.0686     0.0000      0.3737      1.0684
x1             3.1646     0.1843     17.175     0.0000      2.8035      3.5258
x2             1.6738     0.2305     7.2610     0.0000      1.2220      2.1257
                    Equation: eq2, Dependent Variable: y2
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      1.8083     0.1578     11.463     0.0000      1.4991      2.1175
x1             3.9568     0.1565     25.286     0.0000      3.6501      4.2634
x2            -0.8481     0.1523    -5.5682     0.0000     -1.1467     -0.5496
==============================================================================

Covariance Estimator:
Heteroskedastic (Robust) Covariance (Debiased: False, GLS: True)
SystemResults, id: 0x17a929160

{'eq1': 'y1 ~ 1 + x1 + x2', 'eq2': 'y2 ~ 1 + x1 + x2'}