In [1]:
import pandas as pd
solar_installs = pd.read_csv('Data/Solar_Footprints_V2_7811899327930675815.csv')

In [2]:
solar_installs.sort_values(by='Shape__Area', ascending=False)

,OBJECTID,County,Acres,Install Type,Urban or Rural,Combined Class,Distance to Substation (Miles) GTET 100 Max Voltage,Percentile (GTET 100 Max Voltage),Substation Name GTET 100 Max Voltage,HIFLD ID (GTET 100 Max Voltage),...,Percentile (GTET 200 Max Voltage),Substation Name GTET 200 Max Voltage,HIFLD ID (GTET 200 Max Voltage),Distance to Substation (Miles) CAISO,Percentile (CAISO),Substation CASIO Name,HIFLD ID (CAISO),Solar Technoeconomic Intersection,Shape__Area,Shape__Length
2771,2772,Riverside County,7438.603255,Ground,Rural,Ground - Rural,3.886829,50th to 75th,Blythe Walc,304454.0,...,50th to 75th,Colorado River,303761.0,6.290021,50th to 75th,Colorado River,303761.0,Outside,3.010313e+07,35928.275147
5387,5388,Kings County,5058.074647,Ground,Rural,Ground - Rural,2.932513,50th to 75th,Unknown,309129.0,...,0 to 25th,Unknown,309129.0,3.605828,25th to 50th,Henrietta,304664.0,Outside,2.046914e+07,21487.606885
2804,2805,Riverside County,3875.067318,Ground,Rural,Ground - Rural,2.513474,25th to 50th,Unknown,300795.0,...,0 to 25th,Unknown,300795.0,4.587985,25th to 50th,Kem,306318.0,Outside,1.568186e+07,22390.045184
3339,3340,San Bernardino County,3444.751330,Ground,Rural,Ground - Rural,30.154816,75th to 100th,Sandy Valley,NaN,...,75th to 100th,Camino,305759.0,0.000000,0 to 25th,Ivanpah,310135.0,Outside,1.394046e+07,23319.291206
1362,1363,Kings County,2894.855803,Ground,Rural,Ground - Rural,1.486667,25th to 50th,Unknown,309129.0,...,0 to 25th,Unknown,309129.0,2.166880,0 to 25th,Henrietta,304664.0,Outside,1.171514e+07,22346.529151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4278,4279,Santa Clara County,0.034271,Rooftop,Urban,Rooftop - Urban,0.876115,0 to 25th,Ames Distribution,310434.0,...,25th to 50th,Ravenswood,308197.0,7.727228,50th to 75th,Scott,300561.0,Within,1.386912e+02,53.207933
5160,5161,Kern County,0.029450,Ground,Rural,Ground - Rural,6.904726,75th to 100th,Whirlwind,306225.0,...,50th to 75th,Whirlwind,306225.0,6.904726,50th to 75th,Whirlwind,306225.0,Outside,1.191793e+02,49.438403
5166,5167,Kern County,0.017946,Ground,Rural,Ground - Rural,6.659845,75th to 100th,Whirlwind,306225.0,...,50th to 75th,Whirlwind,306225.0,6.659845,50th to 75th,Whirlwind,306225.0,Outside,7.262562e+01,34.145689
5167,5168,Kern County,0.007517,Ground,Rural,Ground - Rural,6.266930,75th to 100th,Whirlwind,306225.0,...,50th to 75th,Whirlwind,306225.0,6.266930,50th to 75th,Whirlwind,306225.0,Outside,3.042128e+01,158.366524
5179,5180,Kern County,0.000413,Ground,Rural,Ground - Rural,7.633457,75th to 100th,Whirlwind,306225.0,...,50th to 75th,Whirlwind,306225.0,7.633457,50th to 75th,Whirlwind,306225.0,Outside,1.671917e+00,20.319768

In [17]:
solar_installs.groupby('County')['Acres'].sum().sort_values(ascending=False)

County
Kern County               31120.012374
Riverside County          27407.234213
Imperial County           16433.794820
San Bernardino County     16015.421073
Kings County              15900.618199
Los Angeles County        11084.963558
Fresno County              8462.816938
San Luis Obispo County     4749.201895
Tulare County              3302.904574
Merced County              2436.533156
Monterey County            1835.785914
Sacramento County          1770.111219
Stanislaus County          1653.878766
San Benito County          1228.380798
San Diego County           1191.473327
Madera County               802.517314
Santa Clara County          505.015307
Santa Barbara County        485.401797
Orange County               470.806142
San Joaquin County          456.849181
Contra Costa County         425.123837
Alameda County              407.018556
Solano County               361.158083
Ventura County              248.286281
Yolo County                 217.161747
Sonoma County               183.848100
Butte County                128.993951
Placer County               112.831812
San Mateo County             97.725542
Sutter County                89.925110
Tehama County                89.430099
Napa County                  81.856675
Shasta County                67.995709
Lassen County                64.805645
El Dorado County             47.687918
Yuba County                  42.248733
Inyo County                  40.166585
Marin County                 37.093280
Lake County                  35.301270
Glenn County                 28.059016
Colusa County                25.710354
San Francisco County         23.254412
Santa Cruz County            16.976018
Mendocino County             15.140347
Tuolumne County              12.951892
Humboldt County              10.310052
Amador County                 9.747331
Nevada County                 5.226320
Mono County                   4.619613
Plumas County                 4.530443
Calaveras County              1.741138
Name: Acres, dtype: float64

In [ ]:
import pandas as pd
wind_farms = pd.read_csv('Data/List_of_Cal_Wind_Farms.csv')

In [12]:
wind_farms.groupby('County')[' Capacity (MW) '].sum().sort_values(ascending=False)

County
Kern              3613.2
Solano            1013.7
Riverside          642.4
Alameda            285.6
Imperial           265.4
San Diego          182.1
Shasta             101.2
Santa Barbara       95.3
Contra Costa        38.0
Merced              18.4
Monterey            14.9
San Bernardino       7.2
San Joaquin          3.5
Los Angeles          1.9
Tehama               1.0
Yolo                 1.0
Name:  Capacity (MW) , dtype: float64

In [44]:
import requests

#response = requests.get(url='https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Kern%20County%2C%20California/2024-03-05?unitGroup=us&key=WBYSNYE8RBY4LYJEAUQE463GZ&contentType=json')

#response.json()

In [ ]:

import requests
import pandas as pd
import time

# Download weather data from NSRDB Database

#Specify names of places with coordinates (Longitude Latitude) as a dictionary

coords = {"sanfrancisco":"(-122.42 37.78)"}
#"imperial": "(-115.57 32.8)"
#"kings": "(-119.65 36.32)"
#"kern" : "(-119.01 35.38)"
#"riverside": "(-117.37 33.98)"
#"sanbernardino":"(-117.29 34.1)"
#"losangeles":"(-118.25 34.04)"
#"solano":"(-122.04 38.25)"
#"alameda":"(-122.27 37.805)"
#"sandiego":"(-117.16 32.71)"
#"sacramento":"(-121.49 38.58)"
#"santaclara":"(-121.89 37.34)"
#"sanfrancisco":"(-122.42 37.78)"

#Data only available for years 2018 through 2023
years = ['2023', '2022', '2021', '2020', '2019', '2018']


BASE_URL = "https://developer.nrel.gov/api/nsrdb/v2/solar/nsrdb-GOES-full-disc-v4-0-0-download.csv"

params = {
    #"wkt": "POINT(-115.57 32.8)",  # Location in WKT format
    #"names": "2022",
    "utc": "false",  # Local time
    "leap_day": "true",  # Include leap day
    "email": "shabari@umich.edu",  # Replace with your registered email
    "interval": "10",
    "full_name": "Shabarish Chenakkod",
    "affiliation": "University of Michigan",
    "api_key": "APIKEY"  # Replace with your actual API key
}

for key, val in coords.items():
    for year in years:
        params['wkt'] = 'POINT'+val
        params['names'] = year
        print(params)
        response = requests.get(BASE_URL, params=params)
        with open("Data/NSRDB_API_Downloads/"+key+'_'+year+".csv", "w") as file:
            file.write(response.text)
        print('Downloaded data for '+key+'_'+year)
        time.sleep(20)

{'utc': 'false', 'leap_day': 'true', 'email': 'shabari@umich.edu', 'interval': '10', 'full_name': 'Shabarish Chenakkod', 'affiliation': 'University of Michigan', 'api_key': '650V5tg2nYv8lCe5dulOWOs6DnsYm30BQSSkxxtP', 'wkt': 'POINT(-122.42 37.78)', 'names': '2023'}
Downloaded data for sanfrancisco_2023
{'utc': 'false', 'leap_day': 'true', 'email': 'shabari@umich.edu', 'interval': '10', 'full_name': 'Shabarish Chenakkod', 'affiliation': 'University of Michigan', 'api_key': '650V5tg2nYv8lCe5dulOWOs6DnsYm30BQSSkxxtP', 'wkt': 'POINT(-122.42 37.78)', 'names': '2022'}
Downloaded data for sanfrancisco_2022
{'utc': 'false', 'leap_day': 'true', 'email': 'shabari@umich.edu', 'interval': '10', 'full_name': 'Shabarish Chenakkod', 'affiliation': 'University of Michigan', 'api_key': '650V5tg2nYv8lCe5dulOWOs6DnsYm30BQSSkxxtP', 'wkt': 'POINT(-122.42 37.78)', 'names': '2021'}
Downloaded data for sanfrancisco_2021
{'utc': 'false', 'leap_day': 'true', 'email': 'shabari@umich.edu', 'interval': '10', 'full_name': 'Shabarish Chenakkod', 'affiliation': 'University of Michigan', 'api_key': '650V5tg2nYv8lCe5dulOWOs6DnsYm30BQSSkxxtP', 'wkt': 'POINT(-122.42 37.78)', 'names': '2020'}
Downloaded data for sanfrancisco_2020
{'utc': 'false', 'leap_day': 'true', 'email': 'shabari@umich.edu', 'interval': '10', 'full_name': 'Shabarish Chenakkod', 'affiliation': 'University of Michigan', 'api_key': '650V5tg2nYv8lCe5dulOWOs6DnsYm30BQSSkxxtP', 'wkt': 'POINT(-122.42 37.78)', 'names': '2019'}
Downloaded data for sanfrancisco_2019
{'utc': 'false', 'leap_day': 'true', 'email': 'shabari@umich.edu', 'interval': '10', 'full_name': 'Shabarish Chenakkod', 'affiliation': 'University of Michigan', 'api_key': '650V5tg2nYv8lCe5dulOWOs6DnsYm30BQSSkxxtP', 'wkt': 'POINT(-122.42 37.78)', 'names': '2018'}
Downloaded data for sanfrancisco_2018

In [10]:
#Combine data for various years into one file

import datetime

years = ['2018', '2019', '2020', '2021', '2022', '2023']
places = ['sanfrancisco']

for place in places:
    weather_data_list = []
    for year in years:
        df = pd.read_csv('Data/NSRDB_API_Downloads/'+place+'_'+year+'.csv', skiprows = 2)
        df['begin_time'] = df.apply(lambda x: datetime.datetime(int(x['Year']), int(x['Month']), int(x['Day']), int(x['Hour']), int(x['Minute']),0) , axis=1)
        weather_data_list.append(df)
    weather_stacked_df = pd.concat(weather_data_list, ignore_index=True)
    weather_stacked_df.to_csv('Data/NSRDB_API_Downloads/'+place+'_stacked_weather_data.csv', index=False)

In [ ]:
#Get data for a particular weather attribute across different places 


from collections import defaultdict
from functools import reduce

places = ['imperial', 'kern', 'kings', 'riverside', 'sanbernardino', 'losangeles']
#places=['imperial']
data_by_places = defaultdict(lambda: pd.DataFrame())

for place in places:
    data_by_places[place] = pd.read_csv('Data/NSRDB_API_Downloads/'+place+'_stacked_weather_data.csv')

weather_attribute = 'Temperature' 

dfs_to_merge=[]
for place in places:
    dfs_to_merge.append((place, data_by_places[place][['begin_time', weather_attribute]]))
initialcolumn = weather_attribute+'_'+places[0]
data_by_attribute = reduce(lambda x, y: ('', pd.merge(x[1], y[1], on='begin_time', how='inner', suffixes=(None, '_'+y[0]))),  dfs_to_merge)[1].rename(columns={weather_attribute:initialcolumn})

data_by_attribute.to_csv('Data/stacked_'+weather_attribute+'_data.csv', index=False)

In [ ]:



def preprocess_power_data(year):
     """
     Preprocesses power price and generation data for a given year and quarter.

     Parameters:
         year (int): The year (e.g., 2023).
         quarter (str): The quarter in 'QX' format (e.g., 'Q1').

     Returns:
         tuple: Processed price and generation DataFrames or (None, None) if files are missing.
     """
     # Correct LMP file path (for zones)
     lmp_dam_path = f"Data/unproc/caiso_lmp_da_hr_zones_{year}.csv"

#     # Preprocessed output folder
     output_dir = f"Data/preprocessed/"
     os.makedirs(output_dir, exist_ok=True)  # Ensure directory exists

#     # Debugging: Print file paths to verify correctness
     print(f"Checking files:\n  {lmp_dam_path}")

#     # Check if files exist
     if not os.path.exists(lmp_dam_path):
         print(f"Error: Price data file not found: {lmp_dam_path}")
         return None, None


#     # Load and preprocess price data
     pricedata = pd.read_csv(lmp_dam_path, skiprows=3)
     pricedata.rename(columns={'Local Timestamp Pacific Time (Interval Beginning)': 'begin_time'}, inplace=True)
     pricedata['begin_time'] = pd.to_datetime(pricedata['begin_time'])
#     pricedata = pricedata[pricedata['begin_time'].dt.minute % 10 == 0]  # Filter to 10-minute intervals

#     # Save preprocessed price data
     price_output_path = os.path.join(output_dir, f"preprocessed_lmp_da_{year}.csv")
     pricedata.to_csv(price_output_path, index=False)
     print(f"✅ Saved: {price_output_path}")



     return pricedata

# # Process all years from 2020 to 2024
years = range(2020, 2025)

for year in years:
    year_str = f"{year}"
    print(f"\nProcessing {year_str}...")
    preprocess_power_data(year)

print("\n✅ All data from 2020Q4 to 2025Q1 successfully processed and saved!")

Processing 2020...
Checking files:
  Data/unproc/caiso_lmp_da_hr_zones_2020.csv
✅ Saved: Data/preprocessed/preprocessed_lmp_da_2020.csv

Processing 2021...
Checking files:
  Data/unproc/caiso_lmp_da_hr_zones_2021.csv
✅ Saved: Data/preprocessed/preprocessed_lmp_da_2021.csv

Processing 2022...
Checking files:
  Data/unproc/caiso_lmp_da_hr_zones_2022.csv
✅ Saved: Data/preprocessed/preprocessed_lmp_da_2022.csv

Processing 2023...
Checking files:
  Data/unproc/caiso_lmp_da_hr_zones_2023.csv
✅ Saved: Data/preprocessed/preprocessed_lmp_da_2023.csv

Processing 2024...
Checking files:
  Data/unproc/caiso_lmp_da_hr_zones_2024.csv
✅ Saved: Data/preprocessed/preprocessed_lmp_da_2024.csv

✅ All data from 2020Q4 to 2025Q1 successfully processed and saved!

In [21]:
import os
import pandas as pd

# Define the base directory for Load Forecast data
base_path = "Data/unproc/"

# Define available years
years = [2020, 2021, 2022, 2023, 2024]

# Initialize a list to store dataframes
load_forecast_data_list = []

# Loop through each year and process data
for year in years:
    file_path = os.path.join(base_path, f"caiso_gen_ren_hr_{year}.csv")

    if os.path.exists(file_path):  # Check if file exists before loading
        df = pd.read_csv(file_path, skiprows=3, delimiter=",")
        df["year"] = year  # Add a year column
        load_forecast_data_list.append(df)
        print(f"✅ Loaded: {file_path}")
    else:
        print(f"❌ Missing file: {file_path}")

# Concatenate all available Load Forecast data
if load_forecast_data_list:
    stacked_load_forecast_data = pd.concat(load_forecast_data_list, ignore_index=True)

    # Save the stacked dataset
    output_file_path = "Data/preprocessed/stacked_gen_ren_hr_data.csv"
    stacked_load_forecast_data.to_csv(output_file_path, index=False)
    print(f"✅ Stacked Load Forecast data saved to: {output_file_path}")

else:
    print("❌ No files were found. Please check the directory.")

✅ Loaded: Data/unproc/caiso_gen_ren_hr_2020.csv
✅ Loaded: Data/unproc/caiso_gen_ren_hr_2021.csv
✅ Loaded: Data/unproc/caiso_gen_ren_hr_2022.csv
✅ Loaded: Data/unproc/caiso_gen_ren_hr_2023.csv
✅ Loaded: Data/unproc/caiso_gen_ren_hr_2024.csv
✅ Stacked Load Forecast data saved to: Data/preprocessed/stacked_gen_ren_hr_data.csv

In [18]:
import pandas as pd

river_klamath = pd.read_csv('Data/sacramento.csv', skiprows=25, sep='\t')
print(river_klamath.dtypes)
river_klamath = river_klamath.drop(index=0)
river_klamath['datetime'] = pd.to_datetime(river_klamath['datetime'])
river_klamath.rename(columns={'datetime': 'begin_time'}, inplace=True)
river_klamath.rename(columns={'236032_00060': 'flow'}, inplace=True)
river_klamath

agency_cd          object
site_no            object
datetime           object
tz_cd              object
236032_00060       object
236032_00060_cd    object
dtype: object

/var/folders/y1/qbgxvx6j1vj5ydy42yxx7fsm0000gn/T/ipykernel_99077/3232753346.py:3: DtypeWarning: Columns (1,4) have mixed types. Specify dtype option on import or set low_memory=False.
  river_klamath = pd.read_csv('Data/sacramento.csv', skiprows=25, sep='\t')

       agency_cd   site_no          begin_time tz_cd     flow 236032_00060_cd
1           USGS  11447650 2020-01-01 00:00:00   PST    18200               A
2           USGS  11447650 2020-01-01 00:15:00   PST    17900               A
3           USGS  11447650 2020-01-01 00:30:00   PST    18100               A
4           USGS  11447650 2020-01-01 00:45:00   PST    17900               A
5           USGS  11447650 2020-01-01 01:00:00   PST    18500               A
...          ...       ...                 ...   ...      ...             ...
175383      USGS  11447650 2025-01-01 22:45:00   PST  56000.0               P
175384      USGS  11447650 2025-01-01 23:00:00   PST  56000.0               P
175385      USGS  11447650 2025-01-01 23:15:00   PST  56000.0               P
175386      USGS  11447650 2025-01-01 23:30:00   PST  56000.0               P
175387      USGS  11447650 2025-01-01 23:45:00   PST  56000.0               P

[175387 rows x 6 columns]

In [19]:
river_klamath[['begin_time', 'flow']].to_csv('Data/preprocessed/sacramento_river_discharge.csv', index=False)

In [18]:
import pandas as pd

natural_gas_price = pd.read_csv('Data/Henry_Hub_Natural_Gas_Spot_Price.csv', skiprows=4)
natural_gas_price.rename(columns={'Henry Hub Natural Gas Spot Price Dollars per Million Btu':'Natural_gas_price'}, inplace=True)
natural_gas_price['Day'] = pd.to_datetime(natural_gas_price['Day'])
natural_gas_price = natural_gas_price[::-1]
natural_gas_price.set_index('Day', inplace=True)
dates = pd.date_range(start=natural_gas_price.index.min(), end=natural_gas_price.index.max(), freq='1h')
natural_gas_price = natural_gas_price.reindex(dates)
natural_gas_price['Natural_gas_price'] = natural_gas_price['Natural_gas_price'].ffill()
natural_gas_price.reset_index(inplace=True)
natural_gas_price.rename(columns={'index':'begin_time'}, inplace=True)
natural_gas_price.head(50)
natural_gas_price.to_csv('Data/preprocessed/nat_gas_price.csv', index=False)

In [21]:
base_path = "Data/unproc/"

# Define the range of years and quarters
years = range(2021, 2025)  # Covers 2020 to 2025
quarters = ["Q1", "Q2", "Q3", "Q4"]

# Initialize a list to store dataframes
price_data_list = []

# Loop through each year and quarter to load and append preprocessed LMP data
for year in years:
    for quarter in quarters:
        quarter_str = f"{year}{quarter}"
        if quarter_str < "2020Q4" or quarter_str > "2025Q1":  # Skip out-of-range quarters
            continue

        # Construct the correct file path
        file_path = f"Data/unproc/caiso_lmp_rt_5min_zones_{year}{quarter}.csv"

        # Load the file
        df = pd.read_csv(file_path, skiprows=3)
        df["quarter"] = quarter_str  # Add a column to identify the quarter
        price_data_list.append(df)
        print(f"✅ Loaded: {file_path}")

# Concatenate all LMP price dataframes into a single dataframe
stacked_lmp_data = pd.concat(price_data_list, ignore_index=True)

# Define the output path for the stacked LMP data
output_file_path = "Data/preprocessed/stacked_lmp_price_data.csv"

# Save the stacked dataframe as a CSV file
stacked_lmp_data.to_csv(output_file_path, index=False)
print(f"✅ Stacked LMP price data saved to: {output_file_path}")

✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2021Q1.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2021Q2.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2021Q3.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2021Q4.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2022Q1.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2022Q2.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2022Q3.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2022Q4.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2023Q1.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2023Q2.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2023Q3.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2023Q4.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2024Q1.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2024Q2.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2024Q3.csv
✅ Loaded: Data/unproc/caiso_lmp_rt_5min_zones_2024Q4.csv
✅ Stacked LMP price data saved to: Data/preprocessed/stacked_lmp_price_data.csv